version: "3.7" # 파일 규격 버전
volumes:
  ginza-dbdata:
  ginza-elasticsearch:
services:
  # DB
  postgresql:
    image: "postgres:alpine"
    container_name: ginza-db
    restart: always
    volumes:
      - ginza-dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password1234 # only local use
      - POSTGRES_USER=ginza
      - POSTGRES_DB=ginzadb
      - TZ= "Asia/Seoul"
  # Redis
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: ginza-cache
    hostname: localhost
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

  # Elastic Search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: ginza-elasticsearch
    volumes:
      - ginza-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

  #kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: ginza-kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"

  #filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.2
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./applogs:/usr/share/filebeat/logs
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - kibana
      - elasticsearch
    depends_on:
      - elasticsearch