name: Django CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  
  continuous-deployment:
    runs-on: ubunto-latest
    needs: [continuous-integration]
    steps:
      # Step1
      - name: Configure AWS Credentials
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
    # Step 2  
      - name : Create CodeDeploy deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name ginza-api-dev \
          --deployment-group-name ginza-api \
          --deployment-config-name CodeDeployDefault.OneAtTime \
          --github-location repository=${{ github.repository }} , commitId=${{ github.sha }}
